version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpassword
      POSTGRES_DB: cloudcosts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud-net

networks:
  cloud-net:
    driver: bridge

volumes:
  postgres_data: 